# Generated by Django 2.2.4 on 2019-08-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='membership_expire_date',
            new_name='member_expiration_date',
        ),
    ]
