# Generated by Django 2.2.4 on 2019-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20190814_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_out',
            field=models.CharField(default='', max_length=1),
        ),
    ]
