# Generated by Django 2.2.4 on 2019-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_book_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_out_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='due_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
